name: Generate badges
on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  Badge-generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Your original steps
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Linter checker
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit:coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage-summary.json
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
